# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodePrep', '0002_auto_20180321_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
